# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouthFirstCate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('政策法规', '政策法规'), ('创业就业', '创业就业'), ('权益保障', '权益保障'), ('教育成长', '教育成长'), ('人文科技', '人文科技'), ('身心健康', '身心健康'), ('理想信念', '理想信念'), ('党建团建', '党建团建'), ('社团生活', '社团生活'), ('生活休闲', '生活休闲'), ('情感家庭', '情感家庭'), ('unknown', 'unknown')], default='unknown', max_length=255, unique=True, verbose_name='一级类目')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
            options={
                'verbose_name_plural': '青年之声一级类目关系表',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='YouthForumData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=100, verbose_name='问题文本')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated')),
                ('first_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpustag.YouthFirstCate', verbose_name='一级类目')),
            ],
            options={
                'verbose_name_plural': '青年之声人工标注语料库',
                'ordering': ['update_date'],
            },
        ),
        migrations.CreateModel(
            name='YouthSecondCate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('政策法规', [['时事热点', '时事热点'], ['国情政策', '国情政策'], ['经济政治', '经济政治'], ['文化社会', '文化社会'], ['生态文明', '生态文明'], ['法律法规', '法律法规']]), ('创业就业', [['职场人际', '职场人际'], ['创业就业方向', '创业就业方向'], ['创业资质', '创业资质'], ['创业团队', '创业团队'], ['创业项目', '创业项目'], ['创业投资', '创业投资'], ['工作机会', '工作机会'], ['求职面试', '求职面试'], ['实习兼职', '实习兼职']]), ('权益保障', [['妇女权益保障', '妇女权益保障'], ['劳动者权益保障', '劳动者权益保障'], ['消费者权益保护', '消费者权益保护'], ['社会保障', '社会保障'], ['未成年人保护', '未成年人保护'], ['预防未成年人犯罪', '预防未成年人犯罪'], ['知识产权保护', '知识产权保护']]), ('教育成长', [['校园教育', '校园教育'], ['家庭教育', '家庭教育'], ['社会教育', '社会教育'], ['考研出国', '考研出国'], ['校园生活', '校园生活']]), ('人文科技', [['哲学社会', '哲学社会'], ['文学艺术', '文学艺术'], ['历史地理', '历史地理'], ['科学技术', '科学技术'], ['工业技术', '工业技术'], ['运输工程', '运输工程'], ['环境安全', '环境安全']]), ('身心健康', [['保健养生', '保健养生'], ['美容健体', '美容健体'], ['身体健康', '身体健康'], ['心理咨询', '心理咨询'], ['体育运动', '体育运动']]), ('理想信念', [['共产主义', '共产主义'], ['社会主义', '社会主义'], ['爱国主义', '爱国主义'], ['人生观', '人生观'], ['价值观', '价值观'], ['世界观', '世界观'], ['道德观', '道德观']]), ('党建团建', [['党史党章', '党史党章'], ['团章团史', '团章团史'], ['入党入团', '入党入团'], ['党务工作', '党务工作'], ['团务工作', '团务工作'], ['干部培训', '干部培训'], ['基层团建', '基层团建']]), ('社团生活', [['社团组织', '社团组织'], ['学生组织', '学生组织'], ['公益活动', '公益活动'], ['志愿服务', '志愿服务'], ['社会实践', '社会实践']]), ('生活休闲', [['衣食住行', '衣食住行'], ['户外休闲', '户外休闲'], ['娱乐活动', '娱乐活动'], ['数码游戏', '数码游戏'], ['生活服务', '生活服务']]), ('情感家庭', [['亲情', '亲情'], ['友情', '友情'], ['爱情', '爱情'], ['婚姻', '婚姻'], ['孕产', '孕产'], ['育儿', '育儿']]), ('unknown', 'unknown')], default='unknown', max_length=255, unique=True, verbose_name='二级类目')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('first_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpustag.YouthFirstCate')),
            ],
            options={
                'verbose_name_plural': '青年之声二级类目关系表',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='youthforumdata',
            name='second_class',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='first_class', chained_model_field='first_class', on_delete=django.db.models.deletion.CASCADE, to='corpustag.YouthSecondCate', verbose_name='二级类目'),
        ),
    ]
