# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpustag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.CharField(choices=[('教育成长', (('校园生活', '校园生活'), ('考研出国', '考研出国'))), ('党建团建', (('团务工作', '团务工作'), ('党务工作', '党务工作'))), ('unknown', 'unknown')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=2000),
        ),
    ]
