# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpustag', '0002_auto_20170803_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tag',
        ),
        migrations.AddField(
            model_name='question',
            name='first_class',
            field=models.CharField(choices=[('教育成长', '教育成长'), ('党建团建', '党建团建')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='second_class',
            field=models.CharField(choices=[('校园生活', '校园生活'), ('考研出国', '考研出国'), ('团务工作', '团务工作'), ('党务工作', '党务工作'), ('unknown', 'unknown')], default='unknown', max_length=20),
        ),
    ]
