# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpustag', '0004_auto_20170804_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthforumdata',
            name='first_class',
            field=models.CharField(choices=[('教育成长', '教育成长'), ('党建团建', '党建团建'), ('创业就业', '创业就业'), ('情感家庭', '情感家庭'), ('人文科技', '人文科技'), ('身心健康', '身心健康'), ('社团生活', '社团生活'), ('理想信念', '理想信念'), ('政策法规', '政策法规'), ('生活休闲', '生活休闲'), ('权益保障', '权益保障'), ('unknown', 'unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='youthforumdata',
            name='second_class',
            field=models.CharField(choices=[('教育成长', (('校园教育', '校园教育'), ('家庭教育', '家庭教育'), ('社会教育', '社会教育'), ('考研出国', '考研出国'), ('校园生活', '校园生活'))), ('党建团建', (('团务工作', '团务工作'), ('党务工作', '党务工作'))), ('unknown', 'unknown')], default='unknown', max_length=20),
        ),
    ]
